import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../Characteristics')))

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../AircraftGeneral')))

# def heat_convection(airframe=Airframe()):
#     altitude = 60000 # Altitude in foot
#     c_p = 1.005  # Specific heat capacity of air in J/(kg*K)
#     g = 9.81  # Gravitational acceleration in m/s^2
#     k = 0.0257  # Thermal conductivity of air in W/(m*K)
#     mu = 1.43226e-5  # Dynamic viscosity of air in kg/(m*s)
#     rho = 0.1153  # Density of air in kg/m^3
#     t = 0.01 # thickness of the material in meters
#     delta_T = 70  # Difference Temperature in Kelvin
#     beta = 1/293 # Volumetric expansion coefficient of air in 1/K
#     C = 1.32 # formula coefficient
#     n = 0.25 # formula exponent


#     Gr = (rho**2 * g * beta * c_p *delta_T * t**3) / (mu**2) # Grashof number
#     Pr = (c_p * mu) / k # Prandtl number
#     Ra = Gr * Pr # Rayleigh number
#     Nu = C * Ra**n # Nusselt number
#     h = (Nu * k) / t # Convective heat transfer coefficient in W/(m^2*K)

#     S = airframe.S # Surface area in m^2

#     S_reference =  2 * airframe.S # Reference surface area for heat transfer in m^2

#     Q = h * S_reference * delta_T # Heat transfer rate in Watts
#     return Q

# print("Heat transfer rate (Q) in Watts:", heat_convection())



def battery_heat_dissipation():
    I = 2.36 # Current in Amperes
    ACIR = 0.020 # Average Current Internal Resistance in Ohms
    DCIR = ACIR / 0.7 # DC Internal Resistance in Ohms
    P = I**2 * DCIR # Power dissipated as heat in Watts
    return P

def battery_efficiency():
    I = 2.36 # Current in Amperes
    V = 3.45 # Average charge voltage in Volts
    ACIR = 0.020 # Average Current Internal Resistance in Ohms
    DCIR = ACIR / 0.7 # DC Internal Resistance in Ohms
    delta_V = I * DCIR # Power loss due to internal resistance in Watts
    Average_charge_voltage = V + delta_V # Average charge voltage considering internal resistance in Volts
    Average_discharge_voltage = V - delta_V # Average discharge voltage considering internal resistance in Volts
    Efficiency = (Average_discharge_voltage / Average_charge_voltage) # Efficiency of the battery
    return Efficiency


# print("Battery efficiency:", battery_efficiency())
#
# aircraft_instance = Aircraft()


# print(aircraft_instance.compute_subsys_pow())

def number_batteries_required(Pow_req=1200.0):
    Pow_battery = 2.36 * 3.45 * battery_efficiency() # Power provided by each battery in Watts
    n_batteries_required = Pow_req / Pow_battery # Number of batteries required to meet the power requirement
    return n_batteries_required

def heat_conduction(Pow_req=1200.0, S=35.0):
    k = 0.017  # Thermal conductivity of used foam in W/(m*K)
    t = 0.03/2 # thickness of the aerogel in meters
    delta_T = 70.0  # Difference Temperature in Kelvin
    n_batteries = number_batteries_required(Pow_req) / 2 # Number of batteries per wingsection (assuming 2 sections)
    Q_battery = battery_heat_dissipation() * n_batteries # Heat generated by all batteries in Watts

    Q_heatengines = 2 * (k * S * 0.15 * delta_T / 4.5 ) / t # Heat transfer rate to account for by engines in worst case scenario in Watts

    Q_required = 2 * ((k * S * 0.15 * delta_T / 4.5 ) / t - Q_battery) # Required heat transfer rate in Watts

    return Q_required, Q_heatengines

# print("Required heat transfer rate (Q) in Watts:", heat_conduction()[0])
